### ISSUE TITLE
[Bug] Pixie villages blacklist works opposite than intended

### ISSUE THREAD

**Issue by Dasawkem** [Rebirth-of-the-Night/Ice_and_Fire#12]
Hey there! First of all, I have to say I love this fork of Ice and Fire.

That being said: your newest version seems to have a simple bug, from what I've tested: the blacklist works as the whitelist and vice versa. By default without any changes, even though you intended it to be a whitelist and it states itself as being such, for me it acts as a blacklist and will spawn pixie villages everywhere BUT the base 3 biomes specified. When changed to "false" to make it what it states is a blacklist, it will then act like a whitelist instead. Tested it via creating new worlds and disabling and enabling whitelist, both with base assigned biomes and custom ones, to which they'd act opposite than intended.

I'm willing to bet it's just a mistake or something, but if it's not able to be replicated on your end it could be some odd error with mod conflicts on my end, perhaps. In that case, I'm happy to provide my modlist and any other details needed.

**Comment by AsterixxxGallier** [comment]
I'm testing right now and it doesn't even check, so the blacklist/whitelist is completely broken. I'll release a fix in the next hours, but it might take CurseForge some time to approve the new version (although it only took five minutes last version)

**Comment by AsterixxxGallier** [comment]
I think I found the bug, testing again

**Comment by AsterixxxGallier** [comment]
fixed

**Comment by AsterixxxGallier** [comment]
new version uploaded to CurseForge and queued for approval

**Comment by AsterixxxGallier** [comment]
approved, took only a minute, big props to CurseForge for this (fixed version is 1.9.1-1.1.1, get it now while it's still fresh!)
