### ISSUE TITLE
When I added the module, it crashed and deleted the module

### ISSUE THREAD

**Issue by ainlzj** [Rebirth-of-the-Night/Ice_and_Fire#13]
This is an error repor
[minecraft-exported-logs-2022-01-23T23-34-40.log](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/7920761/minecraft-exported-logs-2022-01-23T23-34-40.log)
t

**Comment by democat3457** [comment]
did you install LLibrary https://www.curseforge.com/minecraft/mc-mods/llibrary/files/3116493

**Comment by ainlzj** [comment]
OK  thanks

**Comment by democat3457** [comment]
gonna assume this is fixed
