### ISSUE TITLE
Amphithere server crash

### ISSUE THREAD

**Issue by Sereath** [Rebirth-of-the-Night/Ice_and_Fire#16]
One of my players started crashing the server just by exploring.

https://gist.github.com/Aeron216/0f398671b4c4fff284844dd9f5c2e35d

And it would crash again as soon as that same player reconnected.

https://gist.github.com/Aeron216/277efbf779e2f469f3d77a661d79021d

I had to forcibly despawn every Amphithere with InControl and have kept it that way ever since.

**Comment by Raptor22a** [comment]
I'm also getting the same crash in singleplayer. I guess I'll have to disable their spawning for now.

**Comment by democat3457** [comment]
Fixed by #24
