### ISSUE TITLE
Hippogryph disappears near a dropped Enchanted Berry

### ISSUE THREAD

**Issue by MartinKjunior** [Rebirth-of-the-Night/Ice_and_Fire#18]
No error message.

Dropping the item Enchanted Berry (that is supposed to be used to tame Hippogryph) deletes all Hippogryphs in the area. When tested with 10, they disappeared one by one in a quick succession rather than instantly all at once. The Berry needs to be close enough for the bug to work. Dropping it from a large height above a Hippogryph will only delete it once the Berry gets close.

Pls fix, my heart cannot take more disappointment trying to gain flight in this modpack.

**Comment by Pandahoro** [comment]
getting this problem as well, also tested to see if it was the berries, changed the config file back to rabbits foot and they still left me like my dad on that one sunday morning

**Comment by democat3457** [comment]
Fixed by #24
