### ISSUE TITLE
Village Crash

### ISSUE THREAD

**Issue by IC-Dyllac** [Rebirth-of-the-Night/Ice_and_Fire#19]
When flying through a world in creative, game crashed as a village was appearing. Relaunched the world and village didn't generate save for a few blocks.
To my understanding crashed happened when the game tried to spawn the Snow Villager. I tried spawning it myself with the egg, but it didn't spawn and threw an error.

Crash Log (with lots of mods loaded):  [Crash-Log](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/8599598/crash-2022-05-01_13.54.31-server.txt)

Latest log where only this mod is loaded (and tried spawning the snow villager): [NotSoLatest.log](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/8599602/NotSolatest.log)

**Comment by democat3457** [comment]
Closed with #21
