### ISSUE TITLE
Cockatrice crash.

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/Ice_and_Fire#27]
See report, modlist in it.
https://pastebin.com/84cDwjz4

**Comment by Orf1** [comment]
This issue has been resolved in [this commit](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/a406d37510371fd40a68e293ec37de762fdae3c1) and should be gone in the next release. If you want to fix this bug immediately, feel free to replace the current Ice_and_Fire mod with the new jar. You can find that here:  [IceAndFireRotN-1.9.1-1.1.3.jar](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/raw/master/mods/IceAndFireRotN-1.9.1-1.1.3.jar)

**Comment by MagmaSlime123** [comment]
Thank you.
