### ISSUE TITLE
Crash on startup after update 1.2.1

### ISSUE THREAD

**Issue by ALJ323** [Rebirth-of-the-Night/Ice_and_Fire#29]
https://pastes.dev/fFOw8PIHQg

**Comment by democat3457** [comment]
does this happen with 1.2.0

**Comment by democat3457** [comment]
and if not, did you update anything else when you updated i&f, because i suspect its a mod conflict as it works just fine in an isolated install

**Comment by freopt** [comment]
I have the same issue, and the game launches fine on 1.2.0

**Comment by democat3457** [comment]
@freopt what's your modlist

**Comment by freopt** [comment]
[2022-05-28-1.log](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/8791542/2022-05-28-1.log)
heres the log where it crashed
modlist is in log

**Comment by democat3457** [comment]
is this latest.log or debug.log (if it's latest, id like debug)

clearly theres something modifying the ModelBase class to change the textureWidth and textureHeight variables

**Comment by freopt** [comment]
[debug-3.log](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/8791564/debug-3.log)

**Comment by democat3457** [comment]
I reuploaded 1.2.1, try now

**Comment by freopt** [comment]
It launches fine now

**Comment by democat3457** [comment]
amazing
