### ISSUE TITLE
no fire dragon breath fire particles

### ISSUE THREAD

**Issue by ralseilii** [Rebirth-of-the-Night/Ice_and_Fire#37]
the fire dragon's breath fire particles don't appear , but  the ice dragon's breath ice particles appear, and this only occurs in the RotN version

**Comment by ralseilii** [comment]
I am using the latest versions of the library and the Ice and Fire Rotten version, and I haven't installed any other mods, but the issue with the lack of dragon breath particles still exists.This is very unfriendly to players trying to kill the Fire Dragon, because not being able to see its breath often leads to inadvertently running out of health.

**Comment by Mellohi138** [comment]
Trying to do some tweaks for better code readability had caused this issue, you won't encounter it in the next version to be released

**Comment by democat3457** [comment]
Fixed in 1.3.0
