### ISSUE TITLE
[CRASH] Ice and fire ROTN Pixie house crash the game trying to render it

### ISSUE THREAD

**Issue by ElTioYisus** [Rebirth-of-the-Night/Ice_and_Fire#4]
-Install only ice and fire rotn version and library to see that there is the problem.
-On creative go to ice and fire blocks tab and try to see the pixies house.
-Complete! Your game is crashed.

Additionally i have tested that is the item the problem, the block placed looks to not crash the game (im still not sure).

**Comment by democat3457** [comment]
Can you send the crash report

**Comment by AsterixxxGallier** [comment]
part of much bigger problems of the fork which I'm getting back to rn, but I do know exactly what causes this error so no worries about that

**Comment by AsterixxxGallier** [comment]
solved locally now, will be cleaning up a little more and then build and publish a patched version on CF

**Comment by AsterixxxGallier** [comment]
released a patched version on CF
