### ISSUE TITLE
Dragon AI is very weird.

### ISSUE THREAD

**Issue by MagmaSlime123** [Rebirth-of-the-Night/Ice_and_Fire#41]
It seems dragon AI is acting very weird. They fly in a straight line into the distance then de-spawn. Happens every time a nest with a dragon generates. Happens ever since Lightning Dragons came out, as per #36.

Happens with/without other mods.

(Would show a video but I don't want it being 50 GBs of me just flying around till I find a nest.)

**Comment by sainagh** [comment]
To add to this, they always try to fly towards spawn chunks.

I have also seen them teleport directly to spawn chunks (only seen lightning dragons do if this can help narrow things down).
