### ISSUE TITLE
DRagon AI related crash

### ISSUE THREAD

**Issue by Zack7292** [Rebirth-of-the-Night/Ice_and_Fire#42]
So, i have a weird crash caused by the Dragon mob's AI, this bug was already present on the base ice and fire mod (had the same crash with it): [crash log]( https://mclo.gs/9StHbUD)

according to a guy which helped me with my modpack a bit he's told me that it was caused by this:

This VerifyError error indicates a problem in the bytecode generated for the EntityDragonBase class.

More specifically, this appears to be due to an inconsistency in the stackmaps generated by the compiler.

The mapping tables are used to check at each code branch that the stack (stack of method calls) is in the expected state. Here a check fails at line 461 during a "goto" code jump.

Some possible causes:

     Bytecode compilation problem (faulty Java compiler)

     Version mismatch between compiled classes and Java runtime

     Error in the source code which disrupts the generation of stackmaps

     Bytecode modified invalidly after compilation

To resolve:

     Recompile the problematic class
     Update Java dependencies
     Check the source code of EntityDragonBase
     Clean and regenerate full bytecode

This is often due to problems assembling classes from different versions/sources. Recompiling should resolve the inconsistency.

modpack (will be updated with the proper mod selection later today -> mod will be there but disabled): https://legacy.curseforge.com/minecraft/modpacks/infinitely-exploring

**Comment by democat3457** [comment]
You can try 1.3.1. However, I suspect this is caused by some other mixin overwriting a constructor that I&F uses, so it's not strictly I&F's fault, considering that I&F works in a clean install. I don't have the time to look into which mod of yours is causing this- if you do find it, you can reopen this issue
