### ISSUE TITLE
Lightning Dragonsteel tools are bugged

### ISSUE THREAD

**Issue by Xvareon** [Rebirth-of-the-Night/Ice_and_Fire#49]
The lightning dragonsteel axe, shovel, pickaxe, and hoe freezes targets like an ice dragonsteel tool.

To reproduce:
Hit targets with said tools

Intended behavior:
Said tools should summon dragon lightning bolt like the sword does.

**Comment by Xvareon** [comment]
![Screenshot_2023_1215_141825.png](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/assets/91329439/0033f15a-689e-4393-8ba3-92f11fa91332)

I think the solution is to just return just the "this.toolID" on the ItemModX.java files

X being Axe,Shovel,Pickaxe, and Hoe. This will also fix the other issue with the icedragonsteel and myrmex tools

**Comment by democat3457** [comment]
Fixed by https://github.com/Rebirth-of-the-Night/Ice_and_Fire/commit/6b305b33fb923247cbd8a19150c0bc10777622a0
