### ISSUE TITLE
Ice dragonsteel tools are bugged too

### ISSUE THREAD

**Issue by Xvareon** [Rebirth-of-the-Night/Ice_and_Fire#50]
The ice dragonsteel axe, shovel, pickaxe, and hoe burns targets like a fire dragonsteel tool.

To reproduce:
Hit targets with said tools

Intended behavior:
Said tools should freeze targets like the sword does.

**Comment by Xvareon** [comment]
![Screenshot_2023_1215_141825.png](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/assets/91329439/9c7cfbc7-426c-4db8-8596-6fe4e5c069a0)


I think the solution is to just return just the "this.toolID" on the ItemModX.java files

X being Axe,Shovel,Pickaxe, and Hoe.

**Comment by democat3457** [comment]
Fixed by https://github.com/Rebirth-of-the-Night/Ice_and_Fire/commit/6b305b33fb923247cbd8a19150c0bc10777622a0
