### ISSUE TITLE
Incompatible with RL-Mixin mod after Ice and Fire RotN v1.2.0

### ISSUE THREAD

**Issue by KnightCa** [Rebirth-of-the-Night/Ice_and_Fire#51]
**Is there an existing issue for this?**
I have searched the existing issues and not found any

**Observed behavior**:
I have been able to run Minecraft for quiet sometime on v1.2.0.
After updating to v1.3.1 (no other mod changes), the Client crashes during startup.

Ice and Fire RotN version: [IceAndFireRotN-1.9.1-1.3.1](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition)
Updated from: [IceAndFireRotN-1.9.1-1.2.0](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition)

**Forge version**
1.12.2-forge-14.23.5.2860

**Other mods**
[llibrary-1.7.20-1.12.2](https://www.curseforge.com/minecraft/mc-mods/llibrary)
[RLMixins-1.2.19](https://www.curseforge.com/minecraft/mc-mods/rlmixins)

Below you can see the involved logs:
- [Crash Log](https://gist.github.com/KnightCa/047fc1fdd92352ce62b04e6b7e2657ae)
- [Debug Log](https://gist.github.com/KnightCa/d7a34641aa63f9147c430ccc65d4a975)

**Results**:
I was able to determine the specific incompatibility:

RL Mixins is currently incompatible with:
- Ice and Fire: RotN Edition after v1.2.0

-----------------------------------------------------------

RL Mixins is compatible with:
- Ice and Fire: RotN Edition v1.2.0 (released 5/2022)

as long as the following RL Mixins configs are set to false:
- Enable Better Dragon Bites (IceAndFire)
- InF Offhand Items (IceAndFire)

**Comment by KnightCa** [comment]
I was able to determine the specific incompatibility:

RL Mixins is incompatible with:
* Ice and Fire: RotN Edition after v1.2.0

If the following RL Mixins configs are set to false:
* Enable Better Dragon Bites (IceAndFire)
* InF Offhand Items (IceAndFire)
the following version is compatible:
* Ice and Fire: RotN Edition v1.2.0 (released 5/2022)

**Comment by democat3457** [comment]
This fork fixes many bugs with the original Ice and Fire mod that RL Mixins also tries to fix, causing the crash you experienced. Because RL Mixins is specifically designed for RLCraft and this fork has no intention of using RL Mixins, this incompatibility is not something that will be fixed.

**Comment by KnightCa** [comment]
If you set these RL Mixins configs to false:
* Lycanite Targetting (LycanitesMobs/IceAndFire)
* Stoned Chicken Feather Fix (Quark/IceAndFire)

then RL Mixins is fully compatible with the latest version of Ice and Fire:
* Ice and Fire: RotN Edition v1.9.1-1.3.2

Thank you so much to the developer for the amazing work.
