### ISSUE TITLE
[Bug] Villagers Taking Myrmex as A Profession

### ISSUE THREAD

**Issue by APerson7** [Rebirth-of-the-Night/Ice_and_Fire#8]
**Version:** 1.0.1
**Other Mods:** Happens without any other mods (besides LLibrary), some screenshots were taken with mods for better visibility.
**Forge:** 14.23.5.2860
**The Bug:** With this fork of Ice and Fire installed, vanilla Villagers will spawn with professions such as "Jungle Myrmex Queen" or "Desert Myrmex Royal." This does not happen with the original mod. When using a mod like [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme), every Myrmex variant is listed as a profession. An example from an instance with other mods will be provided below:
![professionexample](https://user-images.githubusercontent.com/53496153/147720546-705c5ee7-c675-424f-9511-ad500d8e2738.PNG)

**Screenshots:**
![2021-12-29_15 45 27](https://user-images.githubusercontent.com/53496153/147720309-5c068b95-4d45-409a-a3f5-4b1b5ecb2f09.png)
![2021-12-29_19 51 53](https://user-images.githubusercontent.com/53496153/147720352-50b790f4-9b8a-49c0-bc94-5ffb1e6edf57.png)
![2021-12-29_19 51 57](https://user-images.githubusercontent.com/53496153/147720353-c2c55acf-5a50-4892-a9cf-4c5624dd850b.png)
![2021-12-29_19 52 17](https://user-images.githubusercontent.com/53496153/147720355-843932c7-f7cd-44f0-b80a-52f8f9e691fa.png)

**Video:**
https://youtu.be/LNMvyrvGONA

**Comment by AsterixxxGallier** [comment]
I'm the author of the fork and I made some minor changes in how professions are registered in IaF, although they are not supposed to have any effect; I'll take a look and if I don't forget about this, it'll be in the next version of the fork
thank you for reporting

**Comment by APerson7** [comment]
No problem, thanks for the response!

**Comment by Dasawkem** [comment]
Commenting here to reiterate that I am also having this issue!

**Comment by democat3457** [comment]
> When using a mod like [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme), every Myrmex variant is listed as a profession. An example from an instance with other mods will be provided below...

@APerson7 can you provide the TellMe log for the original mod?

**Comment by APerson7** [comment]
> @APerson7 can you provide the TellMe log for the original mod?

[villagerprofessions_2022-01-25_21.02.38.txt](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/7939050/villagerprofessions_2022-01-25_21.02.38.txt)
Here you go, seems like vanilla I&F doesn't add any professions that tellme can detect, possible because they're generally used only on non-vanilla villager mobs. I suppose that would make Fishermen, Shamans, and Craftsmen appearing as a normal villager profession part of this bug as well.

Just for comparison, here's the file with the RoTN Edition professions (plus several other mods' professions):
[villagerprofessions_2021-12-29_15.45.42.txt](https://github.com/Rebirth-of-the-Night/Ice_and_Fire/files/7939074/villagerprofessions_2021-12-29_15.45.42.txt)

**Comment by democat3457** [comment]
Interesting, thanks!
